fix: replace yaml.load with yaml.safe_load
Now, the load() function requires parameter loader=Loader, which leads to `TypeError: load() missing 1 required positional argument: 'Loader'` for this tool.